Update workflow.yaml

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -18,11 +18,11 @@ jobs:
     - name: Run
       run: |
         exit 0
-  fail:
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
-    steps:
-    - uses: actions/checkout@v4
-    - name: Run
-      run: |
-        exit 1
+  # fail:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Run
+  #     run: |
+  #       exit 1
